### ISSUE TITLE
Items with charges does not show up (SuperWoW)

### ISSUE THREAD

**Issue by Azzc0** [Cinecom/ConsumesManager#2]
I assume that this is a bug when using SuperWoW and could very well be wrong.
SuperWoW adds visible charges to some items (and doesn't play well with guildbank). Consumes Manager shows that I have 0 Brilliant Mana Oil wheras I've got two full and one with 3 charges.

**Comment by Cinecom** [comment]
Yeah it's a known issue with SuperWoW. I'm looking into it and hopefully have a fix soon

**Comment by Cinecom** [comment]
Fixed
